### ISSUE TITLE
Figure Out Branching Strategy

### ISSUE THREAD

**Issue by GiorgosNik** [AngelPn/e-commerce-platform#4]

**Comment by AngelPn** [comment]
I suggest we follow the [Atlassian branching strategy ](https://www.atlassian.com/agile/software-development/branching) to align with Agile methodologies, focusing on CI/CD.

# Workflow Visualization

-  Main Branch (`main`): Stable and always ready to deploy.
- Development Branch (`develop`): Integrates all features and prepares for the next release.
- Feature Branch (`feature`): For new features and modifications.
- Bugfix Branch (`bugfix`): Addresses fixes for the production environment.

# How to implement

## Main Branch (`main`)

Reflects a production-ready state and is always deployable.

## Development Branch (`develop`)

 A branch where the source code always reflects a state with the latest delivered development changes for the next release.

- Regularly merge feature branches into develop.
- When the develop branch is ready to go live, it is merged into main and tagged with a release number.

## Feature Branch (`feature`)

Feature branches are typically branched off from the develop branch and are used to develop new features or changes. We can adopt the branching format `feature/new-feature-description`.

## Bugfix Branch (`bugfix`)

Bugfixes as well as feature branches are considered tasks and we can make a PR for each task. Bugfix branches can include code that resolves issues. Format:  `bugfix/bug-fix-description`.

# Later on

After our initial setup, we can include release branches. These branches support preparation for a new production release. They allow for minor bug fixes and preparing meta-data for a release.

WDYT?

**Comment by GiorgosNik** [comment]
I agree with the general structure. In addition, I would suggest implementing branch protections to protect this flow.
The rules could include:

- Only allowing Develop to merge into `main`
- Only allowing Releases to merge into `develop`
- We can discuss if merging bugfixes into feature branches is ok

I can go on ahead and make the branches, and will work with these from now on, but I think that the branch protection rules must be set from your side.
